basePath: /
definitions:
  main.Note:
    properties:
      id:
        type: string
      text:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: easy-swagger example of API server
  title: easy-Swagger example API
  version: "1.0"
paths:
  /notes:
    get:
      consumes:
      - application/json
      description: Responds with an array of notes as JSON
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Note'
            type: array
      summary: Get notes array
      tags:
      - notes
    post:
      consumes:
      - application/json
      description: Add a new note to the array. Returns the new note as JSON.
      parameters:
      - description: New note
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/main.Note'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Note'
      summary: Create note
      tags:
      - notes
  /notes/{id}:
    get:
      consumes:
      - application/json
      description: Responds with a note as JSON
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Note'
      summary: Get note by ID
      tags:
      - notes
swagger: "2.0"
